GET http://localhost:3000/api/albums/searchSpotify/waga

###
GET https://dev-btsr3wtx85v3khds.us.auth0.com/authorize?response_type=code&client_id=XVr4pyJXZAcf7aQtA7P92Wv9FPsUZg10&redirect_uri=http://localhost:3000
###
PATCH http://localhost:3003/api/users/6480e17568a768f0729a1d0a HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFfX1poUEt4MlpVTXJHbGg4eTBwMCJ9.eyJpc3MiOiJodHRwczovL2Rldi1idHNyM3d0eDg1djNraGRzLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NDdhNTllMWZjNjBjNTVlYTg2NDMxYjAiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDozMDAzL2FwaSIsImh0dHBzOi8vZGV2LWJ0c3Izd3R4ODV2M2toZHMudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY4NjY3ODgwNCwiZXhwIjoxNjg2NzY1MjA0LCJhenAiOiJYVnI0cHlKWFpBY2Y3YVF0QTdQOTJXdjlGUHNVWmcxMCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.EAm1d93mshLZHraF7ZV-IIseHEg6upIxLV9D6VKCSJ4p4f6Vdpsdql9Ou4spsjm3_AeWqhTtZRx7kS3XCNaPLor4afvtZubGZYzp5UOu7E4MmBociGcpCKo2au4LdjIY5adWxvhzpBNASHNqFqbcRoCfAF5fxF59sZE9sqtqZXenWTzxEDmVgkgqntujM1FFH9JWfmqm6qO6ljANUObHOsSI8nN_8yApmtBPqTcHJ6DBsbvaNmx-jf_juKd5v3vequMmpsYi-8i4m3lsB7A0PWoPj5YtTmpvRAnwm0OKI6w13pkf_ilqcckgNFiXMtIQTNo5l97rMBH8GCrJvmi1TQ

{
    "nickname": "wagabaga" 
}

