GET http://localhost:3003/api/albumRatings/1/4G
###
POST http://localhost:3003/api/albumRatings/
content-type: application/json

{
    "userID": "3",
    "albumID": "09dajsdf",
    "review": {
        "reviewText": "wagabaga",
        "listenList": "true"
    },
    "trackRatings": [
        {
            "id": "6OmhkSOpKQxpIGx2",
            "rating": 99
        }
    ]
}